language: csharp

matrix:
  include:
    - mono: none
      dotnet: 1.0.0-preview2-1-003177
      env: DOTNETCORE=1
      dist: trusty
      solution: src/SparkPost.Dotnet.sln
      sudo: required
      script:
        - dotnet restore src/SparkPost.Dotnet/SparkPost.Dotnet
        - dotnet build src/SparkPost.Dotnet/SparkPost.Dotnet

    - mono: latest
      solution: src/SparkPost.sln
      before_install:
        - sudo apt-get install nunit-console
      before_script:
        - nuget restore src/SparkPost.sln
      script:
        - xbuild /p:Configuration=Release src/SparkPost.sln
        - nunit-console src/SparkPost.Tests/bin/Release/SparkPost.Tests.dll

